name                = "statusboard"
main                = "index.js"
compatibility_date  = "2025-05-04"

account_id = "350b8c66c41f4a6ef3e90849d75c45bd"
zone_id    = "ca47d4b67ff446f4ca02a6c10a32192c"
route      = "teams.efarag.xyz/statuses*"

[[d1_databases]]
binding       = "STATUS_DB"
database_name = "status"